eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
#springbootadmin 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'  # SpringBootActuator监控暴露所有接口
#网关配置
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth-server
#    api-order:
#      path: /api-order/**
#      sensitiveHeaders:
#      serviceId: order-service
    api-user:
      path: /api-user/**
      serviceId: user-service
    api-good:
      path: /api-score/**
      serviceId: score-service