eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
#springbootadmin 监控
  boot:
    admin:
      client:
        url: http://localhost:5000
management:
  endpoints:
    web:
      exposure:
        include: '*'  # SpringBootActuator监控暴露所有接口
#网关配置
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  ignored-services: '*'
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders: "*"
      serviceId: auth-server
#    api-order:
#      path: /api-order/**
#      sensitiveHeaders:
#      serviceId: order-service
    api-user:
      path: /api-user/**
      sensitiveHeaders:
      serviceId: user-service
    api-good:
      path: /api-score/**
      sensitiveHeaders:
      serviceId: score-service
  add-proxy-headers: true